services:
  api-gateway:
    build:
      context: .
      dockerfile: ./services/api-gateway/Dockerfile
    ports:
      - 8080:8080
    environment:
      EMAIL_SERVICE_URL: amqp://rmuser:rmpassword@rabbitmq:5672/
    depends_on:
      rabbitmq:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: services/api-gateway

  email:
    build:
      context: .
      dockerfile: ./services/email/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: services/email
    deploy:
      mode: replicated
      replicas: 3

  tg:
    build:
      context: .
      dockerfile: ./services/tg/Dockerfile
    ports:
      - 8082:8082
    develop:
      watch:
        - action: rebuild
          path: services/tg

  rabbitmq:
    image: rabbitmq:management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
    ports:
      - 15672:15672
      - 5672:5672

    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 20s
      retries: 5
